# Test

image: node:10.20.1

cache:
  paths:
  - node_modules/

stages:
  - install
  - test
  # - deploy

install_dependency:
  stage: install
  script:
    - yarn

unit_test:
  stage: test
  script:
    - yarn test