paths:
  /api/product/all:
    get:
      tags:
        - Product
      summary: 取得所有產品 For admin
      security:
        - Authentication: []
      responses:
        '200':
          description: 取得產品資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderDetailList:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductInfo'
  
  /api/product/create:
    post:
      tags:
        - Product
      summary: 新增產品 For admin
      security:
        - Authentication: []
      requestBody:
        description: Body內容
        content:
          application/json:
            schema:
              properties:
                $ref: '#/components/schemas/CreateInfo'

      responses:
        '200':
          description: 新增產品
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderDetailList:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductInfo'

  /api/product/:id:
    put:
      tags:
        - Product
      summary: 修改產品 For admin
      parameters:
        - in: path
          name: id
          description: 產品id
          required: true
          schema:
            type: number
      requestBody:
        description: Body內容
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInfo'
      security:
        - Authentication: []
      responses:
        '200':
          description: 取得修改後產品資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderDetailList:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductInfo'
    delete:
      tags:
        - Product
      summary: 刪除產品 For admin
      security:
        - Authentication: []
      parameters:
        - in: path
          name: id
          description: 產品id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 取得刪除後產品資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderDetailList:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductInfo'

components:
  schemas:
    CreateInfo:
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: float
        description:
          type: string
        imageUrl:
          type: string

    ProductInfo:
      type: object
      properties:
        p_id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: float
        imageUrl:
          type: string
        createdAt:
          type:  string
          format: date-time
        updatedAt:
          type:  string
          format: date-time

  securitySchemes:
    Authentication:
      type: apiKey
      name: Authentication
      in: header